### PR TITLE
Fixes, lints, prettier, and upgrades

### LINKED ISSUE #94: Enable linting
The code appears to be un-linted currently, or at minimum the code linting is not consistent with the rest of the organisation's repositories. This issue calls for linting to be enabled in line with our other repositories and the resulting issues to be dealt with.

If linting isn't already active in the CI, it should be enabled similarly to the rest of the organisation.

### PR DESCRIPTION
**Pull request by dcroote**
Painful, but had to be done sooner or later. Closes #94 

tl;dr, this PR:
- Upgrades to node 20
- Adds prettier and @api3/eslint-plugin-commons for linting
- Implements many lints
- Fixes several bugs e.g. the staking text in `components/StakingTrend.tsx`

I tested locally with Docker and a sql db backup like in https://github.com/api3dao/api3-tracker/pull/93#issuecomment-2448994978 and everything seems OK

### CODE REVIEW

**Review by aquarat — APPROVED** [review]
LGTM, with all those changes and fixes we may need to re-process the logs in the DB.
AFAIK the DB contains the contents of blocks. Assuming no trimming is applied we could re-process those blocks without hitting the RPC. WDYT?

Also I've fixed the CI auto-deployment action - but I haven't tested it. I will take a machine snapshot just in case.

Lastly, It may be worth enabling linting checks as part of the GH CI, like we do with other repos :) 

Merging this PR should trigger auto-deployment so probably best to do it while I'm online 😅  (~ 08:00 -> 17:00 UTC)

**Comment by dcroote** [comment]
> LGTM, with all those changes and fixes we may need to re-process the logs in the DB.
AFAIK the DB contains the contents of blocks. Assuming no trimming is applied we could re-process those blocks without hitting the RPC. WDYT?

I don't really have a great intuition on this one, but  it sounds preferable to process from stored block contents..

> Also I've fixed the CI auto-deployment action - but I haven't tested it. I will take a machine snapshot just in case.

Good idea. Has this been done? I wouldn't want to merge before you get a chance

> Lastly, It may be worth enabling linting checks as part of the GH CI, like we do with other repos :)

Done- good idea.

> Merging this PR should trigger auto-deployment so probably best to do it while I'm online 😅 (~ 08:00 -> 17:00 UTC)

No problem (but let me know about the snapshot per above)

**Comment by aquarat** [comment]
> Good idea. Has this been done? I wouldn't want to merge before you get a chance

Hey Derek

Yes the above has been done; we have both a machine snapshot and DB backups. Feel free to merge in the next 8 hours :)

**Comment by aquarat** [comment]
I'm am very happy to say that, after some minor fixes, the auto deployment process worked. It should work without issue in future (the minor issues were unrelated to your changes).

I'll create a task to look at re-running the data processing to apply any fixes.

**Comment by dcroote** [comment]
> I'm am very happy to say that, after some minor fixes, the auto deployment process worked. It should work without issue in future (the minor issues were unrelated to your changes).

Great!

**Pull request merged**
